name: Abstract Expressionism
favicon: null
layout_spectrum: 0.9225852915551513
typography_spectrum: 0.42072804761119187
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9885043643880635
  lightness: 0.8841109490022063
  saturation: 0.60844561830163
  rhythmicContrast: 0.3476366880349815
purpose: []
